### PR TITLE
Implement infinite pagination in EntitiesModel and optimize Pagination component.

### PR DESCRIPTION
**Pull request by EversongWoods**
1. The implementation of infinite pagination in ```EntitiesModel```
2. The optimization of the ```Pagination``` component
3. The performance enhancement by loading only necessary data
4. The UI improvement for better navigation when there are many pages
Pagination

### CODE REVIEW

**Comment by aguacongas** [comment]
We don't need a pagination component just load a new page when the user scroll down if there is more data to load.   
Use a 0 based Skip private field and recompute it on API response for the next call instead of using 1 based CurrentPage.  
Reset the skip field on new filter and that works. this field don't need to be public. it's the internal state of the component.

**Comment by EversongWoods** [comment]
Hey @aguacongas , don't worry too much about the implementation details. The user (#1243) needed to browse more data, and that has now been accomplished. That's all there is to it.

**Comment by AnKa0** [comment]
Hi @aguacongas, I would also prefer a simple pagination component instead of an infinite scroll solution. Most importantly my project is in an urgent need of this feature, no matter which of these solutions are chosen.

**Comment by aguacongas** [comment]
If it only for your needs why do you want to merge your change in this repo ? If you have an urgent need why don't you simply build the solution on your side and use it ?

**Comment by aguacongas** [comment]
@EversongWoods @AnKa0 I fixed the issue in PR #1279

**Pull request closed without merging**
